### Create Group
POST http://localhost:3000/createGroup
Content-Type: application/json

{
    "name":"Hiver"
}

### Consult groups
GET http://localhost:3000/groups

### Afficher le nombre de groupe
GET http://localhost:3000/nbGroup

### Consult one groups
GET http://localhost:3000/group/1

### Update Group
PUT http://localhost:3000/updateGroup/5
Content-Type: application/json

{
    "name": "hiver"
}

### Delete Group
DELETE http://localhost:3000/deleteGroup/5